export const GET_ERRORS = "GET_ERRORS";
export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const GET_PROFILE = "GET_PROFILE";
export const PROFILE_LOADING = "PROFILE_LOADING";
export const PROFILE_NOT_FOUND = "PROFILE_NOT_FOUND";
export const CLEAR_CURRENT_PROFILE = "CLEAR_CURRENT_PROFILE";
export const GET_PROFILES = "GET_PROFILES";
export const GET_WISHLIST = "GET_WISHLIST";
export const WISHLIST_LOADING = "WISHLIST_LOADING";
export const WISHLIST_NOT_FOUND = "WISHLIST_NOT_FOUND";
export const CLEAR_CURRENT_WISHLIST = "CLEAR_CURRENT_WISHLIST";
export const GET_ALL_PROPERTIES = "GET_ALL_PROPERTIES";
export const GET_ALL_PROPERTIES_OF_USER_CITY =
  "GET_ALL_PROPERTIES_OF_USER_CITY";
export const PROPERTY_LOADING = "PROPERTY_LOADING";
